services:
  - type: web
    name: sitec-back
    env: node
    plan: free
    buildCommand: npm install && npm run prisma:generate && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: ALLOWED_ORIGINS
        sync: false
    healthCheckPath: /health
    autoDeploy: false
